# syntax=docker/dockerfile:1.6
# Shared builder base for every per-project worker image.
#
# This image moves the always-present, project-INDEPENDENT cost out of
# every per-project worker build and pays it ONCE:
#   1. apt build packages + rustup + the pinned toolchain, and
#   2. the COMPILED weft engine workspace (`weft-engine` and every
#      third-party crate it pulls: tokio, sqlx, reqwest, clap,
#      tracing-subscriber, hex, ...), built `--release` into
#      `/weft/target`.
#
# Why precompile the workspace here (the load-bearing speedup): every
# generated worker crate path-depends on `/weft/crates/weft-engine`
# (+ weft-core, weft-broker-client, weft-platform-traits) and shares
# the workspace `Cargo.lock`, so its ENTIRE fixed dependency set is a
# subset of what `cargo build --release` of this workspace compiles.
# A per-project build that points `CARGO_TARGET_DIR` at this baked
# `/weft/target` and reuses this `Cargo.lock` finds every engine +
# dependency rlib already fingerprinted-fresh, so it compiles ONLY the
# project-specific crates (the `pkg_<node>` packages + the top worker
# crate). That is the difference between a ~70s cold engine compile on
# every project and a few-seconds project-only compile.
#
# Sharing is safe by construction: the engine + deps are byte-identical
# across all projects (same workspace source, same lock, same
# toolchain), so reuse is correctness-preserving, not a cross-project
# leak. Only the per-project `pkg_<node>` crates vary, and those are
# never baked here; they compile fresh in each per-project build under
# the same target dir, where cargo's content fingerprint keeps them
# correctly partitioned.
#
# Rebuild trigger: the base image tag is content-addressed on the
# WORKER CRATE CLOSURE (`codegen::worker_workspace_crates`: the only
# workspace crates a worker links) plus `Cargo.toml`, `Cargo.lock`,
# `rust-toolchain.toml` and this Dockerfile (see
# `hash::compute_builder_base_hash`). Edit the engine and the tag
# changes, so the setup script rebuilds this base and per-project
# worker Dockerfiles automatically `FROM` the new tag; edit a
# non-worker crate (CLI, dispatcher, tests) and nothing here moves.
#
# Build context: NOT the repo root. The CLI stages
# `.weft-base-context/` (`build::stage_builder_base_context`) holding
# exactly the closure crates, a workspace manifest scoped to them, the
# lock, the toolchain pin, and the generated warm-up crate. The COPY
# paths below read from that staged layout.

FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       ca-certificates curl build-essential pkg-config \
    && rm -rf /var/lib/apt/lists/*

# rustup with `--default-toolchain none`: the pinned toolchain comes
# from `rust-toolchain.toml`, materialized on the first `cargo`
# invocation below.
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- -y --default-toolchain none --profile minimal
ENV PATH="/root/.cargo/bin:${PATH}"

# Bake the workspace at `/weft/`, the same path the per-project build
# context expects (the per-project Dockerfile omits the `COPY weft/`
# and relies on this image's layer instead).
WORKDIR /weft
COPY rust-toolchain.toml ./
COPY Cargo.toml Cargo.lock ./
COPY crates ./crates

# Precompile the WARM-UP crate into the shared `/weft/target`. The warm-up
# crate (generated by `codegen::emit_warmup_crate`) has EXACTLY the
# project-independent dependency set every worker carries: the engine path deps
# (`../weft/crates/*`, resolving to `/weft/crates/*`) plus the fixed crates.io
# deps. Building it at `/work` with `CARGO_TARGET_DIR=/weft/target` and the
# workspace lock pre-cooks every engine + dependency rlib with the SAME crate
# identity + feature unification a real worker triggers, so a per-project build
# (same fixed deps, same lock, same target dir, also at `/work`) reuses them and
# compiles only its `pkg_<node>` crates + the thin top crate.
#
# The compile runs against a PERSISTENT cache mount and the result is
# then copied into `/weft/target` as a real image layer. Two reasons
# for that split:
#   - the layer: per-project builds point CARGO_TARGET_DIR at
#     `/weft/target`, so the precompiled rlibs must live in the image
#     itself (a cache mount would be invisible to them);
#   - the cache: successive base builds (every engine edit mints a new
#     content-addressed tag) reuse the previous build's artifacts, so
#     an engine edit recompiles only the crates it touched instead of
#     the whole dependency tree from cold. Fingerprints stay valid
#     across builds because the staging preserves source mtimes and
#     the in-container paths (/weft, /work) never change.
#
# `{{target_cache_key}}` is substituted by the staging step
# (`build::stage_builder_base_context`) with a hash of Cargo.lock +
# rust-toolchain.toml: a lock or toolchain change starts a FRESH cache
# instead of inheriting the old one. Without the key, the cache (and
# therefore the baked layer, since the whole cache is copied in)
# accumulates every dependency version and toolchain ever built:
# cargo never removes superseded artifacts, so the image would grow
# without bound across months of iteration.
#
# The registry cache id is the base's own, NOT shared with per-project
# worker builds: both sides mount `sharing=locked`, so a shared id
# would serialize a minutes-long base rebuild against every concurrent
# worker build. The one-time cost is re-fetching the crates.io
# artifacts this build needs into its own cache.
# The toolchain materializes implicitly on this first `cargo`
# invocation (rustup reads `rust-toolchain.toml`).
COPY .weft-warmup /work
RUN --mount=type=cache,id=weft-builder-base-cargo-registry,target=/root/.cargo/registry,sharing=locked \
    --mount=type=cache,id=weft-builder-base-target-{{target_cache_key}},target=/cache/target,sharing=locked \
    cp /weft/Cargo.lock /work/Cargo.lock \
    && cd /work \
    && CARGO_TARGET_DIR=/cache/target cargo build --release \
    && mkdir -p /weft/target \
    && cp -a /cache/target/. /weft/target/
