//! Signal-token administration. Token CRUD lives here (mint, list,
//! revoke); kind-specific signal enumeration and firing routes live in
//! `signal.rs` and are general-purpose.
//!
//! Token model (show-once): the value (`wft-` + six words, see
//! `weft_core::signal_token`) is generated by the dispatcher (or the broker, for a
//! member token a program mints), returned EXACTLY ONCE in
//! the mint response, and stored only as a sha256 hash plus a display
//! recognizer. Listing returns metadata only; no endpoint can re-reveal a
//! token. Revocation addresses the token's id, never its value.
//!
//! An external consumer (a client that listens for + answers a project's
//! waiting nodes) hits:
//!   - `POST /signal-tokens` (mint), `GET /signal-tokens` (list),
//!     `DELETE /signal-tokens/{id}` (revoke): tenant-authenticated admin.
//!   - `GET /signal-token/signals`, `DELETE /signal-token/signals`,
//!     `GET /signal-token/health`, and the node displays under
//!     `/signal-token/displays` (`api/display.rs`): the token itself
//!     authenticates, via `Authorization: Bearer wft-...` (never in the
//!     URL, where proxies and access logs would capture it).
//!   - `POST /signal/{token}` (fire), `DELETE /signal/{token}` (cancel):
//!     per-SIGNAL fire tokens, a separate credential whose whole job is to
//!     be a paste-able URL.
//! No kind-specific endpoints in the dispatcher.

use axum::{extract::{Path, State}, http::StatusCode, Json};
use serde::Serialize;

use crate::authenticator::CallerTenant;
use crate::state::DispatcherState;

#[derive(Debug, serde::Deserialize)]
pub struct MintTokenBody {
    /// The user-facing label (a display name), never part of the token value.
    #[serde(default)]
    pub name: Option<String>,
    /// Scope vectors. Empty = wildcard. Each non-empty vector narrows
    /// the signals this token can enumerate. Tags must pass the tag
    /// charset (`[A-Za-z0-9_-]{1,64}`); rejected at parse time.
    #[serde(default, rename = "allowedProjects")]
    pub allowed_projects: Vec<uuid::Uuid>,
    #[serde(default, rename = "allowedTags")]
    pub allowed_tags: Vec<String>,
    /// The display dimension, which does NOT take the wildcard-on-empty
    /// rule: a token says which node displays it may read, or reads
    /// none. `allDisplays` is the wildcard within the token's projects.
    #[serde(default, rename = "allowedDisplays")]
    pub allowed_displays: Vec<String>,
    #[serde(default, rename = "allDisplays")]
    pub all_displays: bool,
    /// A member token: acts as this member of its one project
    /// (`allowedProjects` names exactly that one).
    #[serde(default)]
    pub member: Option<weft_core::member::MemberId>,
    /// How long the token works, in seconds from now. Required for a
    /// member token (it lives in a browser); optional otherwise.
    #[serde(default, rename = "expiresInSecs")]
    pub expires_in_secs: Option<u64>,
}

/// Why a mint request cannot make the token it asks for: a member token
/// names exactly one project and an expiry. How long an expiry may be is
/// `weft_core::signal_token::expiry_at`'s, checked at the mint.
pub(crate) fn check_mint_shape(body: &MintTokenBody) -> Result<(), String> {
    if let Some(member) = &body.member {
        if body.allowed_projects.len() != 1 {
            return Err(format!(
                "a member token acts in exactly one project: name it (--project) for member '{member}'"
            ));
        }
        if body.expires_in_secs.is_none() {
            return Err(format!(
                "a member token lives in a browser, so it needs an expiry (--expires) for member '{member}'"
            ));
        }
    }
    Ok(())
}

/// The mint response: the ONLY place the full token value ever appears.
#[derive(Debug, Serialize)]
pub struct MintedToken {
    pub id: uuid::Uuid,
    /// The full secret, shown once. The client copies it now; the server
    /// keeps only its hash and can never show it again.
    pub token: String,
    pub recognizer: String,
    pub name: Option<String>,
    /// The paste-able connect string for clients that take one URL
    /// (`<public-base>/signal-token/<token>`): clients PARSE it into base +
    /// token and present the token via `Authorization: Bearer`; the wire
    /// requests never carry it in a path.
    pub url: String,
    #[serde(rename = "allowedProjects")]
    pub allowed_projects: Vec<uuid::Uuid>,
    #[serde(rename = "allowedTags")]
    pub allowed_tags: Vec<String>,
    #[serde(rename = "allowedDisplays")]
    pub allowed_displays: Vec<String>,
    #[serde(rename = "allDisplays")]
    pub all_displays: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub member: Option<weft_core::member::MemberId>,
    #[serde(rename = "expiresAtUnix", skip_serializing_if = "Option::is_none")]
    pub expires_at_unix: Option<u64>,
}

/// A listed token: metadata + recognizer only, no secret.
#[derive(Debug, Serialize)]
pub struct TokenSummary {
    pub id: uuid::Uuid,
    pub recognizer: String,
    pub name: Option<String>,
    #[serde(rename = "createdAtUnix")]
    pub created_at_unix: u64,
    #[serde(rename = "allowedProjects")]
    pub allowed_projects: Vec<uuid::Uuid>,
    #[serde(rename = "allowedTags")]
    pub allowed_tags: Vec<String>,
    #[serde(rename = "allowedDisplays")]
    pub allowed_displays: Vec<String>,
    #[serde(rename = "allDisplays")]
    pub all_displays: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub member: Option<weft_core::member::MemberId>,
    #[serde(rename = "expiresAtUnix", skip_serializing_if = "Option::is_none")]
    pub expires_at_unix: Option<u64>,
}

/// Build a token's paste-able connect string from the dispatcher's public base.
fn token_url(public_base: &str, token: &str) -> String {
    format!("{}/signal-token/{token}", public_base.trim_end_matches('/'))
}

pub async fn mint_token(
    State(state): State<DispatcherState>,
    caller: CallerTenant,
    Json(body): Json<MintTokenBody>,
) -> Result<Json<MintedToken>, (StatusCode, String)> {
    use weft_core::signal_token as names;

    let name = body
        .name
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(str::to_string);

    // Validate tag charset on the way in. Same rule as _tags in .weft
    // source so tokens and signals share one vocabulary.
    if let Err(e) = weft_core::tag::validate_tags(&body.allowed_tags) {
        return Err((StatusCode::BAD_REQUEST, format!("allowed_tags: {e}")));
    }
    check_mint_shape(&body).map_err(|why| (StatusCode::BAD_REQUEST, why))?;
    // A member token acts inside its project, so that project has to be
    // the caller's: minting one for a project of another tenant would
    // hand a browser a door into it.
    if body.member.is_some() {
        crate::authenticator::authorize_project(&state, &caller.0, body.allowed_projects[0]).await?;
    }

    // A display grant that cannot reach anything is refused HERE, with
    // the flag still in the person's hand, rather than minting a token
    // that answers 404 forever. What comes back is what gets stored:
    // the node exactly as the person spelled it, under a project id in
    // one canonical form.
    let allowed_displays = crate::api::display::canonical_display_grants(
        &state,
        caller.0.as_str(),
        &body.allowed_projects,
        &body.allowed_displays,
        body.all_displays,
    )
    .await?;

    let now = crate::lease::now_unix() as u64;
    let expires_at = body
        .expires_in_secs
        .map(|secs| names::expiry_at(now, secs))
        .transpose()
        .map_err(|why| (StatusCode::BAD_REQUEST, why))?;
    let token = names::generate_token();
    let signal_token = crate::journal::SignalToken {
        id: uuid::Uuid::new_v4(),
        token_hash: names::token_hash(&token),
        recognizer: names::recognizer(&token),
        tenant_id: caller.0.as_str().to_string(),
        name: name.clone(),
        allowed_projects: body.allowed_projects,
        allowed_tags: body.allowed_tags,
        allowed_displays,
        all_displays: body.all_displays,
        // Stamp the mint time here (the canonical wall clock) and store it
        // verbatim, so both the postgres and fake journals agree instead of one
        // stamping now() and the other keeping a placeholder.
        created_at: now,
        member: body.member,
        expires_at,
    };

    state
        .journal
        .mint_signal_token(&signal_token)
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, format!("journal: {e}")))?;
    let url = token_url(state.external_base_url(), &token);
    Ok(Json(MintedToken {
        id: signal_token.id,
        token,
        recognizer: signal_token.recognizer,
        name,
        url,
        allowed_projects: signal_token.allowed_projects,
        allowed_tags: signal_token.allowed_tags,
        allowed_displays: signal_token.allowed_displays,
        all_displays: signal_token.all_displays,
        member: signal_token.member,
        expires_at_unix: signal_token.expires_at,
    }))
}

pub async fn list_tokens(
    State(state): State<DispatcherState>,
    caller: CallerTenant,
) -> Result<Json<Vec<TokenSummary>>, (StatusCode, String)> {
    let tokens = state
        .journal
        .list_signal_tokens(caller.0.as_str())
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, format!("journal: {e}")))?;
    Ok(Json(
        tokens
            .into_iter()
            .map(|t| TokenSummary {
                id: t.id,
                recognizer: t.recognizer,
                name: t.name,
                created_at_unix: t.created_at,
                allowed_projects: t.allowed_projects,
                allowed_tags: t.allowed_tags,
                allowed_displays: t.allowed_displays,
                all_displays: t.all_displays,
                member: t.member,
                expires_at_unix: t.expires_at,
            })
            .collect(),
    ))
}

pub async fn revoke_token(
    State(state): State<DispatcherState>,
    caller: CallerTenant,
    Path(id): Path<uuid::Uuid>,
) -> Result<StatusCode, (StatusCode, String)> {
    let removed = state
        .journal
        .revoke_signal_token(id, caller.0.as_str())
        .await
        .map_err(|e| (StatusCode::INTERNAL_SERVER_ERROR, format!("journal: {e}")))?;
    if removed {
        Ok(StatusCode::NO_CONTENT)
    } else {
        Err((StatusCode::NOT_FOUND, format!("no token with id {id}")))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn body(member: Option<&str>, projects: usize, expires: Option<u64>) -> MintTokenBody {
        MintTokenBody {
            name: None,
            allowed_projects: (0..projects).map(|i| uuid::Uuid::from_u128(i as u128 + 1)).collect(),
            allowed_tags: vec![],
            allowed_displays: vec![],
            all_displays: false,
            member: member.map(|m| weft_core::member::MemberId::new(m).unwrap()),
            expires_in_secs: expires,
        }
    }

    #[test]
    fn a_member_token_names_one_project_and_an_expiry() {
        assert!(check_mint_shape(&body(Some("ada"), 1, Some(3600))).is_ok());
        assert!(check_mint_shape(&body(Some("ada"), 0, Some(3600))).unwrap_err().contains("exactly one project"));
        assert!(check_mint_shape(&body(Some("ada"), 2, Some(3600))).unwrap_err().contains("exactly one project"));
        assert!(check_mint_shape(&body(Some("ada"), 1, None)).unwrap_err().contains("needs an expiry"));
        assert!(check_mint_shape(&body(None, 0, None)).is_ok());
    }
}
